import type { Metadata } from "next";
import { Cascadia_Code, Geist, Geist_Mono, Lusitana } from "next/font/google";
import "./ui/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const lusitana = Lusitana({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const cascadiaCode = Cascadia_Code({
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adam Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${cascadiaCode.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
